AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

plugins:
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml
