---
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { ruby: '3.3' }
          - { ruby: '3.4' }
          - { ruby: '4.0' }
    name: test (${{ matrix.entry.ruby }})
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.entry.ruby }}
      - run: bundle install --jobs=3 --retry=3
      - run: bundle exec rake spec
